/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package uk.kukino.cq

import java.math.BigInteger


fun hexDump(bytes: ByteArray): String {
    return bytes.joinToString("") { String.format("%02x", it) }
}


fun main(rgs: Array<String>) {

    // https://stackoverflow.com/questions/49825455/ecdsa-signature-java-vs-go

    KeysHelper.init()

    val kp = KeysHelper.getKeyPair()

    println(hexDump(kp.public.encoded))
    println(kp.public)
    println("Public: " + hexDump(KeysHelper.asECPublicKey(kp.public).encoded))

    println(hexDump(kp.private.encoded))
    println(kp.private)
    println("Private: " + KeysHelper.asECPrivateKey(kp.private).s.toString(16))

//    KeyFactory.getInstance("EC").generatePrivate()

    var signature = KeysHelper.sign(kp, "HOLA".toByteArray())
    println(BigInteger(signature).toString(16))
    println(KeysHelper.verify(KeysHelper.asECPublicKey(kp.public), "HOLA".toByteArray(), signature))


}
